# Generated by Django 4.1.4 on 2023-01-19 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('spassw', models.CharField(max_length=50)),
                ('sphno', models.BigIntegerField()),
                ('sem', models.CharField(max_length=50)),
                ('scourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarymanagemantapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Issuebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.CharField(max_length=50)),
                ('enddate', models.CharField(max_length=50)),
                ('studcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarymanagemantapp.course')),
                ('studname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarymanagemantapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=50)),
                ('authname', models.CharField(max_length=50)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarymanagemantapp.course')),
            ],
        ),
    ]
