# Generated by Django 4.1.4 on 2023-01-23 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagemantapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issuedbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.CharField(max_length=50)),
                ('enddate', models.CharField(max_length=50)),
                ('studbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarymanagemantapp.book')),
                ('studname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarymanagemantapp.student')),
            ],
        ),
    ]
